name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
          update-pip: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      # Install Python (uv will use the version in .python-version or pyproject.toml)
      - name: Set up Python
        run: uv python install
        

      # Install dependencies and the project
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # Run your build/test commands
      - name: Run tests
        run: uv run pytest


      - name: Build project
        run: uv build
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/


  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hypernova-sdk/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}